### PR TITLE
Fix wrong interpretation of root delay and dispersion to match spec

### LINKED ISSUE #1222: NTPv5 still uses old interpretation of Root Delay and Root Dispersion
NTPv5 changed how to interpret the bits used in Root Delay and Root Dispersion fields. We currently use the definition from NTPv4 here.

NTPv4 uses 16 integral and 16 fractional bits.

NTPv5 uses 4 integral and 28 fractional bits.

### PR DESCRIPTION
**Pull request by tdittr**
Fixes #1222

### CODE REVIEW

File: ntp-proto/src/time_types.rs [hunk 1]
```diff
@@ -235,6 +235,33 @@ impl NtpDuration {
...
+        assert!(self.duration >= 0);
+
+        // Other then for short implementation this might very well overflow sometimes, we just saturate in that case
+        const MAX_TIME32: NtpDuration = NtpDuration {
+            duration: 0x00_00_00_0F_FF_FF_FF_F0,
+        };
+
+        match self.duration > MAX_TIME32.duration {
+            true => u32::MAX,
+            false => ((self.duration & MAX_TIME32.duration) >> 4) as u32,
```
Comment (tdittr) [inline ntp-proto/src/time_types.rs:260]: Arguably this could just be
```suggestion
            false => (self.duration >> 4) as u32,
```
as the `as u32` already strips the high bits.

File: ntp-proto/src/time_types.rs [hunk 2]
```diff
@@ -235,6 +235,33 @@ impl NtpDuration {
...
+        // as for duration that are too large, saturating is
+        // the safe option.
+        assert!(self.duration >= 0);
+
+        // Other then for short implementation this might very well overflow sometimes, we just saturate in that case
+        const MAX_TIME32: NtpDuration = NtpDuration {
+            duration: 0x00_00_00_0F_FF_FF_FF_F0,
+        };
+
+        match self.duration > MAX_TIME32.duration {
```
Comment (tdittr) [inline ntp-proto/src/time_types.rs:258]: With the change below this could also be simplified to:
```suggestion
        match self.duration > 0x0F_FF_FF_FF_F0 {
```

**Review by davidv1992 — APPROVED** [review]
