### PR TITLE
FreeBSD fixes

### LINKED ISSUE #274: Add support for FreeBSD

### PR DESCRIPTION
**Pull request by valpackett**
It works, including the initial jump :)

Yeah `SCM_REALTIME` I'll need to submit to libc…

Fixes #274

### CODE REVIEW

File: ntp-udp/src/raw_socket.rs [hunk 1]
```diff
@@ -61,7 +61,7 @@ mod set_timestamping_options {
 
     fn configure_timestamping_socket(
         udp_socket: &std::net::UdpSocket,
-        method: TimestampMethod,
```
Comment (folkertdev) [inline ntp-udp/src/raw_socket.rs:64]: why remove the type safety here? this was meant as a safeguard to just passing in integers. An extra method can be added to the enum if that would help.

**Review by folkertdev — COMMENTED** [review]
this is great!

- I left 1 inline comment/question
- yes it would be nice to have that constant in libc. I've found that process to be straightforward.
- I'll try to setup CI here. this is a bit tricky because we need the appropriate linker (because `ring` has a `build.rs`), and this failed earlier for freebsd. but maybe it works now that the code works.
- we'll likely want to merge the macos stuff first, and then merge this into main. this may take a little while

File: ntp-udp/src/raw_socket.rs (hunk 1 above)
Comment (valpackett) [reply ntp-udp/src/raw_socket.rs:64]: Well, because it's not *a timestamp method* (but rather an extra configuration sockopt for an existing one) and it shouldn't be exposed outside of this module… I guess the better option would be like:

```rust
enum SocketOption {
    Method(TimestampMethod),
    #[cfg(target_os = "freebsd")]
    TimestampClock,
}
```

**Comment by folkertdev** [comment]
eh, I'm not sure what happened here? this should have rebased onto `main`. weird

**Comment by folkertdev** [comment]
@valpackett do you have thoughts on how to have users install ntpd-rs on freebsd? We provide deb and rpm installers which put the binary and config in the right place, and configure some permissions and user groups. 

The installers are built with [ploutos](https://github.com/NLnetLabs/ploutos), which does not support freebsd currently. I'm really not sure how easy that would be to add (though we know the NLNet labs folks well, so we can check with them)

In the meantime we could maybe have some instructions that a user would have to perform manually?

**Comment by valpackett** [comment]
It's uncommon for projects to build their own .pkg independently and for anyone to want to install such packages :) Generally someone would submit a port and the official package will exist. It's no big deal, there is no barrier to entry, and for such a high profile project you can be sure someone will show up to do it soon. (I'll drop a link to here in some places in fact.. :D)

ploutos is really just using [cargo-deb](https://crates.io/crates/cargo-deb) and [cargo-generate-rpm](https://crates.io/crates/cargo-generate-rpm), I'm pretty sure nothing like that exists for FreeBSD pkg for the above reason.

File: ntp-udp/src/raw_socket.rs [hunk 2]
```diff
@@ -157,7 +167,10 @@ mod set_timestamping_options {
             }
         };
 
-        configure_timestamping_socket(udp_socket, method, options)?;
+        configure_timestamping_socket(udp_socket, SockOpt::Method(method), options)?;
+
+        #[cfg(target_os = "freebsd")]
+        configure_timestamping_socket(udp_socket, SockOpt::Clock, libc::SO_TS_REALTIME as u32)?;
```
Comment (davidv1992) [inline ntp-udp/src/raw_socket.rs:173]: This results in two calls to configure_timestamping_socket on freebsd, is that desirable?

**Review by davidv1992 — COMMENTED** [review]
Looks good, one question on a weird second call.

File: ntp-udp/src/raw_socket.rs (hunk 2 above)
Comment (davidv1992) [reply ntp-udp/src/raw_socket.rs:173]: Never mind, I see what this is for

**Review by folkertdev — APPROVED** [review]
ok, great. thanks so much for your help here @valpackett !
